---
  chain:
    -
        name: "get_stackstorm_vault_token"
        ref: "bitesize.new_read_secret"
        parameters:
            name: "vault-stackstorm-mgmt"
            namespace: "kube-system"
        publish:
            secret: "{{ get_stackstorm_vault_token.secret }}"
        on-success: "write_stackstorm_vault_token_to_config"
    -
        name: "write_stackstorm_vault_token_to_config"
        ref: "core.local_sudo"
        parameters:
            cmd: "sed -i '/^token:/c\\token: {{ secret }}' /opt/stackstorm/packs/vault/config.yaml"
