---
name: "bitesize_elasticsearch_create"
pack: "bitesize"
description: "Check for for Elasticsearch events to manage from kubernetes thirdpartyresource sensor"
enabled: true

trigger:
  type: "kubernetes.thirdpartyobject"
  parameters: {}

criteria:
  trigger.resource:
    type: "contains"
    pattern: "ADDED"
  trigger.object_kind:
    type: "equals"
    pattern: "Elasticsearch"

action:
  ref: "bitesize.elasticsearch_create_chain"
  parameters:
    payload: "{{trigger}}"
