---
name: "bitesize_elasticsearch_delete"
pack: "bitesize"
description: "Check for elasticsearch domains to delete using kubernetes thirdpartyresource sensor"
enabled: true

trigger:
  type: "kubernetes.thirdpartyobject"
  parameters: {}

criteria:
  trigger.resource:
    type: "contains"
    pattern: "DELETED"
  trigger.object_kind:
    type: "equals"
    pattern: "Elasticsearch"

action:
  ref: "bitesize.elasticsearch_delete_chain"
  parameters:
    payload: "{{trigger}}"
