---
name: "mysql_delete"
pack: "bitesize"
description: "Check for mysql instances to delete using kubernetes thirdpartyresource sensor"
enabled: true

trigger:
  type: "kubernetes.thirdpartyobject"
  parameters: {}

criteria:
  trigger.resource:
    type: "contains"
    pattern: "DELETED"
  trigger.labels.type:
    type: "equals"
    pattern: "mysql.prsn.io"

action:
  ref: "bitesize.mysql_delete_chain"
  parameters:
    payload: "{{trigger}}"
