---
name: "nfs_create"
pack: "bitesize"
description: "Check for NFS cloudformation events to manage from kubernetes thirdpartyresource sensor"
enabled: true

trigger:
  type: "kubernetes.thirdpartyresources"
  parameters: {}

criteria:
  trigger.resource:
    type: "contains"
    pattern: "ADDED"
  trigger.name:
    type: "contains"
    pattern: "nfs"

action:
  ref: "bitesize.nfs_create_chain"
  parameters:
    payload: "{{trigger}}"
