---
name: "nfs_delete"
pack: "bitesize"
description: "Check for NFS cloudformation stacks to delete using kubernetes thirdpartyresource sensor"
enabled: true

trigger:
  type: "kubernetes.thirdpartyresources"
  parameters: {}

criteria:
  trigger.resource:
    type: "contains"
    pattern: "DELETED"
  trigger.name:
    type: "contains"
    pattern: "nfs"

action:
  ref: "bitesize.nfs_delete_chain"
  parameters:
    payload: "{{trigger}}"
