---
name: "pv_delete"
pack: "bitesize"
description: "Delete PVs based on kubernetes PersistentVolumeClaim sensor"
enabled: true

trigger:
  type: "kubernetes.persistentvolumeclaims"
  parameters: {}

criteria:
  trigger.resource:
    type: "contains"
    pattern: "DELETED"
  trigger.object_kind:
    type: "contains"
    pattern: "PersistentVolumeClaim"

action:
  ref: "bitesize.pv_delete_chain"
  parameters:
    payload: "{{trigger}}"
