---
name: "bitesize_rds_delete"
pack: "bitesize"
description: "Check for rds instances to delete using kubernetes thirdpartyresource sensor"
enabled: true

trigger:
  type: "kubernetes.thirdpartyobject"
  parameters: {}

criteria:
  trigger.resource:
    type: "contains"
    pattern: "DELETED"
  trigger.object_kind:
    type: "equals"
    pattern: "Mysql"

action:
  ref: "bitesize.db_delete_chain"
  parameters:
    payload: "{{trigger}}"
