---
name: "redis"
pack: "bitesize"
description: "Check for redis events to manage from kubernetes thirdpartyresource sensor"
enabled: true

trigger:
  type: "kubernetes.thirdpartyobject"
  parameters: {}

criteria:
  trigger.labels.type:
    type: "equals"
    pattern: "redis"

action:
  ref: "bitesize.redis_chain"
  parameters:
    payload: "{{trigger}}"
