---
name: "redis_create"
pack: "bitesize"
description: "Check for redis events to manage from kubernetes thirdpartyresource sensor"
enabled: true

trigger:
  type: "kubernetes.thirdpartyobject"
  parameters: {}

criteria:
  trigger.resource:
    type: "contains"
    pattern: "ADDED"
  trigger.labels.type:
    type: "equals"
    pattern: "redis"

action:
  ref: "bitesize.redis_create_chain"
  parameters:
    payload: "{{trigger}}"
