---
name: "bitesize_route53_create"
pack: "bitesize"
description: "Check for route53 events to manage from kubernetes thirdpartyresource sensor"
enabled: true

trigger:
  type: "kubernetes.thirdpartyobject"
  parameters: {}

criteria:
  trigger.resource:
    type: "contains"
    pattern: "ADDED"
  trigger.labels.type:
    type: "equals"
    pattern: "dns"

action:
  ref: "bitesize.route53_create_chain"
  parameters:
    payload: "{{trigger}}"
