---
name: "kubernetes_cassandra_delete"
pack: "kubernetes"
description: "Check for Cassandra cloudformation stacks to delete using kubernetes thirdpartyresource sensor"
enabled: true

trigger:
  type: "kubernetes.thirdpartyobject"
  parameters: {}

criteria:
  trigger.resource:
    type: "contains"
    pattern: "DELETED"
  trigger.object_kind:
    type: "equals"
    pattern: "Cassandra"

action:
  ref: "kubernetes.cassandra_delete_chain"
  parameters:
    payload: "{{trigger}}"
