---
name: "kubernetes_cassandra_create"
pack: "kubernetes"
description: "Check for Cassandra cloudformation events to manage from kubernetes thirdpartyresource sensor"
enabled: true

trigger:
  type: "kubernetes.thirdpartyobject"
  parameters: {}

criteria:
  trigger.resource:
    type: "contains"
    pattern: "ADDED"
  trigger.object_kind:
    type: "equals"
    pattern: "Cassandra"

action:
  ref: "kubernetes.cassandra_create_chain"
  parameters:
    payload: "{{trigger}}"
