---
name: "kubernetes_redis_delete"
pack: "kubernetes"
description: "Check for redis instances to delete using kubernetes thirdpartyresource sensor"
enabled: true

trigger:
  type: "kubernetes.thirdpartyobject"
  parameters: {}

criteria:
  trigger.resource:
    type: "contains"
    pattern: "DELETED"
  trigger.labels.type:
    type: "equals"
    pattern: "redis"

action:
  ref: "bitesize.delete_redis"
  parameters:
    payload: "{{trigger}}"
