---
name: "kubernetes_route53_create"
pack: "kubernetes"
description: "Check for route53 events to manage from kubernetes thirdpartyresource sensor"
enabled: true

trigger:
  type: "kubernetes.thirdpartyobject"
  parameters: {}

criteria:
  trigger.resource:
    type: "contains"
    pattern: "ADDED"
  trigger.object_kind:
    type: "equals"
    pattern: "Dns"

action:
  ref: "kubernetes.route53_create_chain"
  parameters:
    payload: "{{trigger}}"
