---
name: "kubernetes_testtprs3_create"
pack: "kubernetes"
description: "Check for test thirdparty s3  events to manage from kubernetes thirdpartyresource sensor"
enabled: true

trigger:
  type: "kubernetes.thirdpartyobject"
  parameters: {}

criteria:
  trigger.resource:
    type: "contains"
    pattern: "ADDED"
  trigger.labels.type:
    type: "equals"
    pattern: "testtprs3"

action:
  ref: "kubernetes.testtprs3_create_chain"
  parameters:
    payload: "{{trigger}}"
