---
  name: "new_get_quota_config"
  runner_type: "mistral-v2"
  description: "Look for global, project and namespace quotas, return defaults if none exist"
  enabled: true
  entry_point: "workflows/new_get_quota_config.yaml"
  pack: "bitesize"
  parameters:
    project:
      type: "string"
      description: "project name"
      required: true
    namespace:
      type: "string"
      description: "namespace to setup"
      required: true
    pods:
      type: "string"
      description: "max number of pods"
    services:
      type: "string"
      description: "max number of services"
    replicationcontrollers:
      type: "string"
      description: "max number of replication controllers"
    persistentvolumeclaims:
      type: "string"
      description: "max number of persistent volume claims"
    secrets:
      type: "string"
      description: "max number of secrets"
    resourcequotas:
      type: "string"
      description: "max number of resource quotas"
